site_name: Structured Emersion Theory
site_url: https://structured-emersion-theory.github.io
theme:
  name: material
  palette:
    scheme: slate
    primary: deep purple
    accent: indigo
  features:
    - navigation.tabs
    - navigation.top

nav:
  - Home: index.md
  - Core Docs:
      - Glossary: Glossary.md
      - Equations: Equations.md
      - Law Candidates: law_candidates.md
      - Glossary Candidates: Glossary_Candidates.md
      - Equation Candidates: equation_candidates.md
      - Integration Protocol: Integration_Protocol.md
  - Archive:
      - All Files: archive/
  - Preface:
      - All Files: Preface/
  - Workbench:
      - All Files: Workbench/
  - Modules:
      - All Files: modules/
  - Simulations:
      - All Files: sim/
