site_name: Structured Emersion Theory
site_url: https://structured-emersion-theory.github.io
theme:
  name: material
  palette:
    scheme: slate
    primary: "deep purple"
    accent: indigo
  features:
    - navigation.sections
    - navigation.expand
    - navigation.instant

nav:
  - Home: index.md
  - Preface:
      - Reflections from the Edge: Preface/Reflections_from_the_Edge.md
  - Core Docs:
      - Laws of Structure: core/Laws_of_Structure.md
      - Glossary: core/Glossary.md
      - Equations: core/Equations.md
  - Candidates:
      - Law Candidates: candidates_conflicts/law_candidates.md
      - Glossary Candidates: candidates_conflicts/Glossary_Candidates.md
      - Equation Candidates: candidates_conflicts/equation_candidates.md 
  - Modules:
      - Node Theory: modules/Node_Theory.md
      - Field Collisions: modules/Field_Collisions.md
      - Time & Tempo Sequence: modules/time_tempo_sequence.md
      - Energy from Flicker Pressure: modules/energy_from_flicker_pressure.md
      - Quantum Field Rewrites: modules/quantum_field_rewrites.md
  - Workbench:
      - Charge Field Alignment: Workbench/Charge_Field_Alignment.md
      - Ripple Cascade: Workbench/Ripple_Cascade.md
      - Node Class: Workbench/Node_Class_Differentation.md
      - Tunneling: Workbench/Tunneling_Tempo_Compression.md
  - Simulations:
      - Simulation Notes: sim/Simulation_Notes.md
  - Archive:
      - Meta Reflections: archive/meta_reflections.md
  - For AI Assistants:
      - Integration Protocol: ai_assistants/Integration_Protocol.md
      - Canonical Index: ai_assistants/Canonical_Index.md
      - AI Review Prompt: ai_assistants/AI_Review_Prompt.md