site_name: Structured Emersion Theory
site_url: https://structured-emersion-theory.github.io
theme:
  name: material
  palette:
    scheme: slate
    primary: deep purple
    accent: indigo
  features:
    - navigation.top

nav:
  - Home: index.md
  - Core Docs:
      - Laws of Structure: Laws_of_Structure.md
      - Glossary: Glossary.md
      - Equations: Equations.md
      - Law Candidates: law_candidates.md
      - Glossary Candidates: Glossary_Candidates.md
      - Equation Candidates: equation_candidates.md
      - Integration Protocol: Integration_Protocol.md
  - Archive:
      - Core Concepts: archive/core_concepts.md
      - Equations (Meta): archive/equations.md
      - Meta Reflections: archive/meta_reflections.md
  - Preface:
      - Reflections from the Edge: Preface/Reflections_from_the_Edge.md
  - Workbench:
      - Charge Field Alignment: Workbench/Charge_Field_Alignment.md
      - Ripple Cascade: Workbench/Ripple_Cascade.md
  - Modules:
      - README: modules/README.md
      - Consciousness Field: modules/Consciousness_Field.md
      - Field Collisions: modules/Field_Collisions.md
      - Node Theory: modules/Node_Theory.md
      - Quantum Reframes: modules/Quantum_Reframes.md
      - Time Tempo: modules/Time_Tempo.md
  - Simulations:
      - README: sim/README.md
      - Simulation Notes: sim/Simulation_Notes.md
